var AliveHelper = {
    min_frame: 0,
    max_frame: 0,
	clock_flag: false,
	score_div: null,
	fire_val:60,
	
    init: function() {
        $("#score_container").html('<div style="color:#FFF; text-align:center;"><h4 style="margin:0 0 0 0"><div id="totalscore"></div></h4></div>');
        setTimeout(function() {
            $("body").append('<!-- Email the admin Modal --> <div class="modal fade" id="emailadmin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"> <div class="modal-dialog" role="document"> <div class="modal-content"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> <h4 class="modal-title" id="myModalLabel">Send email to admin</h4> </div> <div class="modal-body"> <div><textarea id="admin_message" class="form-control" placeholder="Enter your message..." rows="5"></textarea></div> <br> </div> <div class="modal-footer"> <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> <button id="send_admin_email" type="button" class="btn btn-primary btn-post-topic">Send</button> </div> </div> </div> </div>');
            $("body").append(' <!-- FAQ Modal --> <div class="modal fade" id="faqmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"> <div class="modal-dialog" role="document"> <div class="modal-content"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> <h4 class="modal-title" id="myModalLabel">Frequently Asked Questions</h4> </div> <div class="modal-body"> <div> <h4 class="text-danger">What is Fire?</h4> Fire is a gas phase chemical reaction with a rapid oxidation process that gives off heat and light. <br> <br> <h4 class="text-danger">What is "Fire Dynamics?" </h4> Fire dynamics is the study of how fires start, spread, and develop . It combines ma fire science, and materials science, as well as disciplines of mechanical engineerin understand how they all interact to affect fire behavior. <br> <br> <h4 class="text-danger">What is the "Fire Triangle?" </h4> The fire triangle is a simple model for understanding fire behavior that illustrates the three elements that a fire needs to ignite: heat, fuel, and oxygen. <br> <br> <h4 class="text-danger">What is the "Fire Tetrahedron?" </h4> The fire tetrahedron constitutes the addition of a component, the chemical chain reaction, to the three already present in the fire triangle. If you do not have this uninhibited chemical reaction, you can get a flash but you cannot have sustained flaming. <br> <br> <h4 class="text-danger">How do we measure fire? </h4> Temperature , heat energy, heat release rate, and heat flux are the units of measurement for fire. • Temperature is measure of the molecular activity of solids, liquids, and gases • Heat energy is needed to change the temperature of an object • Heat release rate is a measure of how much energy is being generated by the fire every second • Heat flux is the amount of energy per unit area that hits the surface <br> <br> <h4 class="text-danger">What are mechanisms of heat transfer? </h4> Heat only gets transferred in one direction - from hot to cold. There are three mech convection, and radiation. • Radiation is the heat transfer by electromagnetic waves • Convection is the heat transfer by the movement of liquids or gasses • Conduction is the heat transfer within solids or between contacting solids Once your PPE is exposed to the cumulative effects of radiant, convective, and conductive heat that lead to flashover, you have only seconds to survive. <br> <br> <h4 class="text-danger">How does heat transfer through gear? </h4> Loose fitting and uncompressed gear takes advantage of the insulation properties of air, so keeping it puffed as much as possible will slow down the rate of heat transfer to your skin. If your gear is compressed, you may not have any air gaps, and heat transfers very quickly with minor loss. This stresses the importance of getting your gear off if you want to cool down. <br> <br> <h4 class="text-danger">What is pyrolysis? </h4> Pyrolysis is the heating of a solid causing it to break down into flammable gas - vapors of unburnt hydroc <br> <br> <h4 class="text-danger">What is heat of combustion? </h4> Heat of comoustion describes the chemical potential energy per unit mass of a fuel. <br> <br> <h4 class="text-danger">How does oxygen impact fire behavior? </h4> When you enrich the environment with oxygen, the fire spread accelerates. When 1 slows down. Without oxygen, heat cannot be produced. <br> <br> <h4 class="text-danger">Does venting cool the fire? </h4> Venting does not always equal cooling. In fact, increasing the availability of oxygen release rate of a fire. <br> <br> <h4 class="text-danger">Does fire double in size every minute? </h4> No. Growth of a fire in a compartment is a function of fuel properties, fuel quantity, compartment geometry, location of fire, and ambient conditions. <br> <br> <h4 class="text-danger">What is flashover? </h4> Flashover is the transition phase in the development of a compartment fire in which surfaces exposed to the thermal radiation from fire gases in excess of 1100°F reach ignition temperature almost simultaneously and the compartment becomes involved in fire from floor to ceiling. <br> <br> <h4 class="text-danger">What is a flow path? </h4> The flow path is the volume between an inlet and an outlet that allows the movement of heat and smoke from the higher pressure within the fire area toward the lower pressure areas accessible via doors and window openings. <br> <br> <h4 class="text-danger">How does wind impact the fire behavior? </h4> In addition to providing the fresh air (oxygen), wind entering the fire apartment drives the fire from the fire location (high-pressure zone) to other parts of the structure (low-pressure zones). Based on varying building configurations, it can create several flow paths within a structure. Operations conducted in the flow path, between the fire and the where the fire wants to go, will place the firefighters at significant risk due to the increased flow of fire, heat, and smoke toward their position. </div> </div> <div class="modal-footer"> <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> </div> </div> </div> </div>    ');
            
            if (app_environment == "TESTING") {
                return 0;
            }

            $('#send_admin_email').click(function() {
                console.log("Sending Admin Email");
                var to = "waqid7@gmail.com";
                var message = $('#admin_message').val();
                message = "Email: " + email + " Message: " + message;
                $.post('mail.php', {
                    email: to,
                    message: message
                });
                $('#emailadmin').modal('hide');
            });
        }, 1000);
		$('.tocExpandCollapse').hide();
		$('#tocFooter').hide();
    },

    register: function() {
        if (app_environment == "TESTING") {
            return 0;
        }

        try {
            if (enable_register == 1 &&
                dept.toString().length > 0 &&
                exp.toString().length > 0 &&
                service_rank.toString().length > 0) {
                email = email_new;
                $('#my_notes_email').val(email);
                $.post("register.php", {
                    module_id: 1,
                    email: email_new,
                    dept: dept,
                    exp: exp,
                    service_rank: service_rank
                }, function(data) {
                    cpCmndNextSlide = true;
                    console.log(data);
                    var obj = $.parseJSON(data);
                    if (obj.status) {
                        session_id = obj.session_id;
                    }
                });
            } else {
                if (dept == 0 || dept.length <= 0) {
                    $('#warning1c').show();
                }
                if (exp == 0 || exp.length <= 0) {
                    $('#warning2c').show();
                }
                if (service_rank == 0 || service_rank.length <= 0) {
                    $('#warning3c').show();
                }
                $.confirm({
                    text: "Please verify your details",
                    confirm: function(button) {
                        // delete();
                    },
                    confirmButton: "OK",
                    post: true,
                    confirmButtonClass: "btn-danger",
                    cancelButtonClass: "btn-default hidden",
                    dialogClass: "modal-dialog modal-lg" // Bootstrap classes for large modal
                });
            }
        } catch (e) {
            $.confirm({
                text: "Please verify your details",
                confirm: function(button) {
                    // delete();
                },
                confirmButton: "OK",
                post: true,
                confirmButtonClass: "btn-danger",
                cancelButtonClass: "btn-default hidden",
                dialogClass: "modal-dialog modal-lg" // Bootstrap classes for large modal
            });
            console.log(e);
        }
    },

    login: function() {
        if (app_environment == "TESTING") {
            return 0;
        }

        try {
            $.post("login.php", {
                email: email_existing
            }, function(data) {
                console.log(data);
                var obj = $.parseJSON(data);
                if (!obj.status) {
                    $.confirm({
                        text: "No such email id exists in our system",
                        confirm: function(button) {
                            // delete();
                        },
                        confirmButton: "OK",
                        post: true,
                        confirmButtonClass: "btn-danger",
                        cancelButtonClass: "btn-default hidden",
                        dialogClass: "modal-dialog modal-lg" // Bootstrap classes for large modal
                    });
                } else {
                    email = email_existing;
                    $('#my_notes_email').val(email);
                    session_id = obj.session_id;
                    $.confirm({
                        text: "Do you want to resume the training?",
                        confirm: function(button) {
                            rdcmndGotoSlide = obj.restore_slide;
                            score = parseInt(obj.score);
                            setTimeout(function() {
                                $('#notes_section').html('<div><input type="email" class="form-control" id="my_notes_email" placeholder="Email"> <textarea id="my_notes" class="form-control" placeholder="Enter your notes..." rows="9" cols="15"></textarea></div> </div> <button id="email_notes" type="button" class="btn-block  btn-post-topic">Send</button>')
                                $('#email_notes').click(function() {
                                    console.log("Emailing notes");
                                    var to = $('#my_notes_email').val();
                                    var notes = $('#my_notes').val();
                                    $.post('mail.php', {
                                        email: to,
                                        notes: notes
                                    });
                                });
                            }, 100);
                        },
                        cancel: function(button) {
                            console.log("Creating new session");
                            $.post("register.php", {
                                module_id: 1,
                                email: obj.email,
                                dept: obj.department,
                                exp: obj.experience,
                                service_rank: obj.service_rank
                            }, function(data) {
                                cpCmndNextSlide = true;
                                console.log(data);
                                var obj = $.parseJSON(data);
                                if (obj.status) {
                                    session_id = obj.session_id;
                                }
                            });
                        },
                        confirmButton: "Yes, Resume my training",
                        cancelButton: "No, Start from beginning",
                        post: true,
                        confirmButtonClass: "btn-danger",
                        cancelButtonClass: "btn-default",
                        dialogClass: "modal-dialog modal-lg" // Bootstrap classes for large modal
                    });
                }
            });
        } catch (e) {
            alert("There seems to be some problem with your internet connection.");
            console.log(e);
        }
    },

    hideTOC: function() {
        cpCmndTOCVisible = false;
        $('.tocExpandCollapse').hide();
    },

    showTOC: function() {
        cpCmndTOCVisible = true;
       // $('.tocExpandCollapse').show();
    },

    saveRestorePoint: function() {
        if (app_environment == "TESTING") {
            return 0;
        }

        $.post("update_restore.php", {
            session_id: session_id,
            restore_slide: cpInfoCurrentSlideIndex
        });
    },

    initSlideStart: function() {
        AliveHelper.min_frame = cpInfoCurrentFrame;
        AliveHelper.max_frame = cpInfoCurrentFrame;
    },

    initNotesWidget: function() {
        $('#notes_section').html('<div height="50px"><b>Notes</b><br><br><textarea id="my_notes" class="form-control" placeholder="Enter your notes here" rows="7" cols="31"></textarea><input type="email" align="left" size="30" class="form-control" id="my_notes_email" placeholder="Enter your email address"> </div> </div> <center><button id="email_notes" type="button" align="center" class="btn-block  btn-post-topic">Send</button></center>');
        
        if (app_environment == "TESTING") {
            return 0;
        }

        $('#email_notes').click(function() {
            console.log("Emailing notes");
            var to = $('#my_notes_email').val();
            var notes = $('#my_notes').val();
            $.post('mail.php', {
                email: to,
                notes: notes
            });
        });
    },

    initClockWidget: function() {
		if(!AliveHelper.clock_flag){
		AliveHelper.clock_flag = true;	
        var startclock = moment().startOf('day');
        var clock = $('#clock_container');

        function tick(t) {
            startclock = moment(t).add(1, 'seconds');
            clock.html("<p style='font-size:16px;color:#fff'>" + startclock.format("HH:mm:ss") + "</p>");
        }
        setInterval(function() {
            tick(startclock);
        }, 1000);
		}
    },

/*     initQuestionSlide: function(quest) {
        setTimeout(function() {
            if (QS["q"+quest+"_a"] == 1 || QS["q"+quest+"_b"] == 1 || QS["q"+quest+"_c"] == 1 || QS["q"+quest+"_d"] == 1) {
                cpCmndPause = true;
                rdcmndPause = true;
            } else {
                cpCmndResume = true;
                rdcmndResume = true;
            }
        }, 100);
    },
 */
    initFire: function(){
		var id = $('#div_Slide div').attr('id');
		$('#'+id).fire({
    speed: 20,
    fireTransparency: AliveHelper.fire_val,
    maxPow: 5,
    gravity: 25,
    flameWidth: 4,
    flameHeight: 1,
    fadingFlameSpeed: 2
});
	},
	
	saveResponse: function(type, quest, ans, sc) {
        if (app_environment == "TESTING") {
            return 0;
        }
		if(sc==25)
		{
		if(AliveHelper.fireVal<100){
		AliveHelper.fireVal = AliveHelper.fireVal+5;
		console.log("fire transparency: "+AliveHelper.fireVal);
		$('.fireJqueryPlugin0Canvas0').fire('change',{fireTransparency: AliveHelper.fireVal});
		}
		}
		else
		{
		if(AliveHelper.fireVal>30)
		{
			AliveHelper.fireVal = AliveHelper.fireVal-5;
			console.log("fire transparency: "+AliveHelper.fireVal);
			$('.fireJqueryPlugin0Canvas0').fire('change',{fireTransparency: AliveHelper.fireVal});
		}
		}

        $.post("quiz.php", {
            session_id: session_id,
            type: type,
            question: quest,
            answer: ans,
            score: sc
        }, function(response) {
            if (response) {
                score += sc;
                $('#totalscore').addClass('animated wobble');
                $('#totalscore').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',
                    function() {
                        AliveHelper.score_div.update(score);
                    });
                setTimeout(function() {
                    $('#totalscore').removeClass('animated wobble');
                }, 2000);
            } else {
                //do nothing
            }
        });
    },

    initScoreWidget: function() {
		
        AliveHelper.score_div = new CountUp("totalscore", score, score, 0, 2);
        AliveHelper.score_div.start();
    },

    initMultiple: function(){
        AliveHelper.showTOC();
        AliveHelper.saveRestorePoint();
        AliveHelper.initNotesWidget();
        AliveHelper.initClockWidget();
        AliveHelper.initScoreWidget();
    }


}